version: '3'

networks:
  aulasexta:

services:
  nginx:
    build: ../nginx/
    image: boscaa/nginx
    ports:
      - "80:80"
    networks:
      - aulasexta

  match-number:
    restart: always
    build: ../match-number/
    image: boscaa/match-number
    ports:
      - "5000"

    container_name: match-number

    networks:
      - aulasexta
  
  match-text:
    restart: always
    build: ../match-text/
    image: boscaa/match-text
    ports:
      - "5000"

    container_name: match-text

    networks:
      - aulasexta

  find-number:
    restart: always
    build: ../find-number/
    image: boscaa/find-text
    ports:
      - "5000"

    container_name: find-number

    networks:
      - aulasexta

  viz:
    image: dockersamples/visualizer
    ports:
      - 8080:8080
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    deploy:
        placement: 
            constraints: [node.role == manager]
